[project]
name = "LolalyticsScraper"
version = "0.0"
requires-python = ">=3.10"
dependencies = [
    "adjustText",
    "requests",
    "numpy",
    "pandas",
    "tqdm",
    "matplotlib",
    "jinja2"
]